#!/usr/bin/env bash
# This script show the record type of a passed subdomain and where it points

foo () {
	if [ -n "$2" ]; then
		dig "$2.$1" | grep -A1 "ANSWER SECTION:" | awk 'NR==2' | awk -v subdomain="$2" '{print "The subdomain " subdomain " is a " $4 " record and points to " $5}'
	else
		dig "www.$1" | grep -A1 "ANSWER SECTION:" | awk 'NR==2' | awk '{print "The subdomain www is a " $4 " record and points to " $5}'
		dig "lb-01.$1" | grep -A1 "ANSWER SECTION:" | awk 'NR==2' | awk '{print "The subdomain lb-01 is a " $4 " record and points to " $5}'
		dig "web-01.$1" | grep -A1 "ANSWER SECTION:" | awk 'NR==2' | awk '{print "The subdomain web-01 is a " $4 " record and points to " $5}'
		dig "web-02.$1" | grep -A1 "ANSWER SECTION:" | awk 'NR==2' | awk '{print "The subdomain web-02 is a " $4 " record and points to " $5}'
	fi
}

foo "$1" "$2"
