#!/usr/bin/env bash
# This script installs nginx web server
# creates index.html file
# start the web server

apt-get update
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
service nginx restart
