#!/usr/bin/env bash
# This script installs nginx web server
# creates html file
# start the web server

apt-get update
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
sed -i '/^server {$/a\\trewrite ^/redirect_me$ http://example.com permanent;\n' /etc/nginx/sites-available/default
service nginx restart
