#!/usr/bin/env bash
# This script installs nginx web server
# creates index.html file
# configures a redirect /redirect_me
# creates 404.html file
# configures a custom 404 page
# start the web server

apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
sed -i "s/server_name _;/server_name _;\n\n\trewrite ^\/redirect_me$ https:\/\/github.com\/ammarelbadry1 permanent;/" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i "s/server_name _;/server_name _;\n\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t}/" /etc/nginx/sites-available/default
service nginx restart
