#!/usr/bin/env bash
# This script installs haproxy load balancer
# configures it so that it sends traffic and distributes it to our web servers

apt-get update
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get install -y haproxy=2.6.\*
sed -i "$ a\\\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver web-01 34.229.66.147:80 check\n\tserver web-02 18.234.145.189:80 check" /etc/haproxy/haproxy.cfg
sed -i "$ a\ENABLED=1" /etc/default/haproxy
service haproxy restart
