#!/usr/bin/env bash
# This script send ICMP ECHO_REQUEST to the network host passed
#+ as an argument if no argument passed an error message appears

if [ "$#" -lt "1" ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi
