#!/usr/bin/env bash
# This script gives you information about the school file.

schoolfile="./school"
if [ -e $schoolfile ]; then
  echo "school file exists"
  if [ ! -s $schoolfile ]; then
    echo "school file is empty"
  else
    echo "school file is not empty"
  fi

  if [ -f $schoolfile ]; then
    echo "school is a regular file"
  fi
else
  echo "school file does not exist"
fi
